//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string CustomerId { get; set; }
        public int ProductNo { get; set; }
        public int Quantity { get; set; }
    }
}
