/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LegacyTaxPayer */

#ifndef _Included_LegacyTaxPayer
#define _Included_LegacyTaxPayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LegacyTaxPayer
 * Method:    getIncomeTax
 * Signature: (S)D
 */
JNIEXPORT jdouble JNICALL Java_LegacyTaxPayer_getIncomeTax
  (JNIEnv *, jobject, jshort);

#ifdef __cplusplus
}
#endif
#endif
