/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StringHelper */

#ifndef _Included_StringHelper
#define _Included_StringHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StringHelper
 * Method:    reverseOf
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_StringHelper_reverseOf
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
